---
- name: pull Rancher/server container
  docker_image:
    name: rancher/rancher
  when: dropbox_installed is success

- name: Create mount volume directories for persistent rancher server data
  file: path={{ item.path }} state=directory mode="a+rw"
  with_items:
      - { path: '/opt/rancher' }

- name: Run Rancher server
  docker_container:
    name: rancher
    image: rancher/rancher
    restart_policy: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /opt/rancher:/var/lib/rancher
      - /opt/rancher/log/:/var/log/

- name: Wait for the Rancher server to start
  action: command docker logs rancher
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10